### ISSUE TITLE
Cannot represent Widget 'EDM Label' (label)

### ISSUE THREAD

**Issue by mdavidsaver** [shroffk/phoebus#547] opened 2019-01-30 22:27 UTC
I'm having difficulty opening a .opi file which was converted from a .edl file.  There are a number of errors reported, and once opened most of the widgets aren't visible.  However, they are still present in the Widgets list, where I can see properties.

```
2019-01-30 14:02:06 SEVERE [org.csstudio.display.builder.representation] Cannot represent Widget 'EDM Label' (label)
java.lang.IndexOutOfBoundsException: Index: 120, Size: 111
        at java.base/java.util.ArrayList.rangeCheckForAdd(ArrayList.java:787)
        at java.base/java.util.ArrayList.add(ArrayList.java:512)
        at com.sun.javafx.collections.ObservableListWrapper.doAdd(ObservableListWrapper.java:101)
        at javafx.collections.ModifiableObservableListBase.add(ModifiableObservableListBase.java:151)
        at com.sun.javafx.collections.VetoableListDecorator.add(VetoableListDecorator.java:320)
        at org.csstudio.display.builder.representation.javafx.widgets.JFXBaseRepresentation.createComponents(JFXBaseRepresentation.java:89)
        at org.csstudio.display.builder.representation.javafx.widgets.JFXBaseRepresentation.createComponents(JFXBaseRepresentation.java:39)
        at org.csstudio.display.builder.representation.ToolkitRepresentation.representWidget(ToolkitRepresentation.java:300)
        at org.csstudio.display.builder.representation.ToolkitRepresentation.representChildren(ToolkitRepresentation.java:273)
        at org.csstudio.display.builder.representation.ToolkitRepresentation.representModel(ToolkitRepresentation.java:257)
        at org.csstudio.display.builder.representation.javafx.JFXRepresentation.representModel(JFXRepresentation.java:577)
        at org.csstudio.display.builder.editor.DisplayEditor.setModel(DisplayEditor.java:531)
        at org.csstudio.display.builder.editor.EditorGUI.lambda$setModel$8(EditorGUI.java:377)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by mdavidsaver** [comment] 2019-01-31 20:12
By a lucky guess I find that if I use BOY to delete the Meter widget from the upper left, then Display Builder loads the rest correctly.  So maybe two issues here.  1) whatever is wrong with the translated Meter widget, and 2) why an error with one widget messes up all (I'm guessing) subsequent widgets.

**Comment by kasemir** [comment] 2019-02-04 17:38
Can you provide the original, converted file that included the meter?
dev_ps_diagnostics.opi.txt already has the meter removed and works fine.

**Comment by mdavidsaver** [comment] 2019-02-04 18:31
Ah, that's because I uploaded the wrong screen.  Here are both the original .edl and re-converted .opi

[etherpsc_ps_diagnostics.edl.txt](https://github.com/shroffk/phoebus/files/2829306/etherpsc_ps_diagnostics.edl.txt)
[etherpsc_ps_diagnostics.opi.txt](https://github.com/shroffk/phoebus/files/2829307/etherpsc_ps_diagnostics.opi.txt)

```sh
$ grep -i Meter /tmp/etherpsc_ps_diagnostics.*
/tmp/etherpsc_ps_diagnostics.edl.txt:# (Meter)
/tmp/etherpsc_ps_diagnostics.edl.txt:object activeMeterClass
/tmp/etherpsc_ps_diagnostics.edl.txt:meterAngle 120
/tmp/etherpsc_ps_diagnostics.opi.txt:  <widget typeId="org.csstudio.opibuilder.widgets.meter" version="1.0">
/tmp/etherpsc_ps_diagnostics.opi.txt:    <name>EDM meter Hulei</name>
```

**Comment by kasemir** [comment] 2019-02-04 19:07
That loads for me.
There are many warnings about colors:
```(readFromXML) - Line 3579 java.lang.Exception: <color> without red```

Those sections have rules which select a named color, missing the fall-back RGB info:
```
<rules>
      <rule name="backColorAlarmRule" out_exp="false" prop_id="background_color">
        <exp bool_exp="pvSev0==-1">
          <value>
            <color name="Invalid"/>
          </value>
        </exp>
        <exp bool_exp="pvSev0==1">
          <value>
            <color name="Major"/>
          </value>
        </exp>
```

Still, it loads, not crashing and then ignoring the rest of the widgets:

![import](https://user-images.githubusercontent.com/1932421/52230715-1e43cf80-2886-11e9-88e1-d19509dfb9d8.png)

Is that the exact file where your version stops reading at the meter?

**Comment by mdavidsaver** [comment] 2019-02-04 21:14
I think we need to talk about versions.  I'm testing 54d5ae84dd9e4eed9306895ef5d39f218abed5f0.  This is a local build, so it is relatively quick for me to update.

> There are many warnings about colors:

It doesn't make any difference for me, but in the interest of completeness.  I have another set of files where I first had EDM expand the color list into RGB files.  [etherpsc_ps_diagnostics_rgb.edl.txt](https://github.com/shroffk/phoebus/files/2829827/etherpsc_ps_diagnostics_rgb.edl.txt) [etherpsc_ps_diagnostics_rgb.opi.txt](https://github.com/shroffk/phoebus/files/2829828/etherpsc_ps_diagnostics_rgb.opi.txt)

**Comment by mdavidsaver** [comment] 2019-02-04 21:16
Opening etherpsc_ps_diagnostics.opi (non-RGB version) shows me:

![meter-fault](https://user-images.githubusercontent.com/4429215/52237666-03219180-287f-11e9-806c-c91f54b99304.png)

**Comment by kasemir** [comment] 2019-02-05 13:04
OK, I see it now.
Note that phoebus doesn't include the more colorful widgets (meter, gauge, ..) which depend on an external library. But everything other than the meter in that display should work, and not fail and then omit a bunch of widgets.
I'll look at it now that I can reproduce the issue.

**Comment by kasemir** [comment] 2019-02-05 14:20
With updates from pull request, it no longer crashes on the missing "meter" widget.
Instead, it shows a gray outline with "<unknown type>".

![missing](https://user-images.githubusercontent.com/1932421/52279239-1d16af00-2927-11e9-8861-481a1f7530f2.png)

**Comment by kasemir** [comment] 2019-03-20 12:36
Closing this since the original issue was handled.

**Closed by kasemir** 2019-03-20 12:36 UTC
