### ISSUE TITLE
alarm server kafka configuration topic management

### ISSUE THREAD

**Issue by shroffk** [shroffk/phoebus#676] opened 2019-05-21 14:54 UTC
Kafka alarm topics were created on a single node installation of kafka using the create_alarm_topics.sh

The kafka server was rebooted as per the instructions to ensure the proper behaviour of the "compact" delete mechanism for the config topic.

While most installations normally work well after the above actions...on some occasions discrepancies are observed between the config topic as seen by the alarm server and as seen by the client

e.g.

![2](https://user-images.githubusercontent.com/2111304/58106678-77760b80-7bb6-11e9-9485-eff7d80e37ed.PNG)
The alarm server sees an alarm configuration with only 2 nodes.

![1](https://user-images.githubusercontent.com/2111304/58106683-78a73880-7bb6-11e9-9df2-d4b8ae1cc220.PNG)
The alarm client at the same time sees 4 nodes (older)

While this is surely a problem with the kafka configuration I have not been able to reliable reproduce this configuration mismatch state. Once this situation arises, a re importing of the alarm configuration resolves the issue.

**Comment by kasemir** [comment] 2019-05-21 15:08
In that situation, what's the output of `monitor_topic.sh XF23ID_OPR`?
Are there eventually null messages for those older nodes to delete them?

**Comment by shroffk** [comment] 2019-05-21 15:24
Currently I have re imported the configuration and this problem is no longer there.
I have set up the logger and I will search the elastic log to see if the null messages were indeed sent out.

**Comment by kasemir** [comment] 2019-06-12 13:47
I suspect the underlying issue is the same as #675. Will describe there.

**Comment by kasemir** [comment] 2019-08-12 17:29
Closing as duplicate of 675

**Closed by kasemir** 2019-08-12 17:29 UTC
